name: my_app
description: A new Flutter application.
version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  sqflite: ^1.1.5
  url_launcher: ^5.0.2
  image_picker: ^0.6.0+3
  provider: ^4.3.2+2
  syncfusion_flutter_charts: ^18.2.57
  supercharged: ^1.10.0
  cloud_firestore: ^0.14.1+3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - images/person.jpg
